"""Add booking fields

Revision ID: c71f8127fe63
Revises: 
Create Date: 2025-02-23 01:07:11.118285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71f8127fe63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('booking_start_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('booking_end_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('equipment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_created')
        batch_op.drop_column('equipment_type')
        batch_op.drop_column('booking_end_time')
        batch_op.drop_column('booking_start_time')
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###
